# -*- coding: utf-8 -*-
"""EEG_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BrbU1moOaFX4LhcBbSvn0KeZbHphJaFg

# DOWNLOADING DATASET
"""

import os
import numpy as np
import pandas as pd
import zipfile
import io
# Set the path to your Bonn EEG dataset folder
data_path1 = "BON_EEG2.zip"
data_path = "BON_EEG"  # Update with your desired extraction folder

# Check if the extraction directory exists, if not, create it
if not os.path.exists(data_path):
    os.makedirs(data_path)

# Unzipping the file
with zipfile.ZipFile(data_path1, 'r') as zip_ref:
    zip_ref.extractall(data_path)

# Load all .txt files from a specific subset (e.g., subset A)
def load_eeg_data(subset):
    subset_path = os.path.join(data_path, subset)
    eeg_signals = []

    # Loop through all files in the subset folder
    for filename in os.listdir(subset_path):
        if filename.endswith(".txt")or filename.endswith(".TXT"):
            file_path = os.path.join(subset_path, filename)
            signal_data = np.loadtxt(file_path)  # Load EEG signal from .txt file
            eeg_signals.append(signal_data)

    return np.array(eeg_signals)

# Load EEG data from all subsets (A, B, C, D, E)
subset_A = load_eeg_data('A')
subset_B = load_eeg_data('B')
subset_C = load_eeg_data('C')
subset_D = load_eeg_data('D')
subset_E = load_eeg_data('E')

# Check the shape of one of the loaded subsets
print(f"Subset E Shape: {subset_E.shape}")  # Expected output: (100, 4097)

import os
import numpy as np
import matplotlib.pyplot as plt

# Path to the directory containing the EEG files
data_path = "BON_EEG"  # Update this with your actual data directory path

# Function to load EEG data from a single file
def load_eeg_signal(file_path):
    return np.loadtxt(file_path)

# Function to plot EEG signals from each subset
def plot_signals_from_each_subset(subset_paths, sampling_rate=173.61):
    plt.figure(figsize=(12, 8))

    for i, subset in enumerate(subset_paths):
        # Load the first EEG signal from each subset
        subset_path = os.path.join(data_path, subset)
        eeg_files = [f for f in os.listdir(subset_path) if f.endswith('.txt') or f.endswith(".TXT")]

        if eeg_files:  # Ensure there are files in the subset directory
            signal = load_eeg_signal(os.path.join(subset_path, eeg_files[0]))
            time = np.arange(len(signal)) / sampling_rate
            #time = np.arange()

            # Plot the signal
            plt.subplot(len(subset_paths), 1, i + 1)
            plt.plot(time, signal, color='blue')
            plt.title(f'EEG Signal from Subset {subset}')
            plt.xlabel("Time (seconds)")
            plt.ylabel("Amplitude")
            plt.grid(True)

    plt.tight_layout()
    plt.show()

# Define subset folders (A, B, C, D, E)
subset_paths = ['A', 'B', 'C', 'D', 'E']

# Plot one signal from each subset
plot_signals_from_each_subset(subset_paths)

"""# DATA PRE-PROCESSING (FILTERING)"""

from scipy import signal

# Define a bandpass filter (e.g., 0.5-40 Hz)
def bandpass_filter(data, lowcut, highcut, fs, order=4):
    nyquist = 0.5 * fs
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = signal.butter(order, [low, high], btype='band')
    filtered_data = signal.filtfilt(b, a, data, axis=1)
    return filtered_data

# Apply bandpass filter to subset A
fs = 173.61  # Sampling frequency for Bonn EEG dataset
lowcut = 0.5  # Lower cutoff frequency
highcut = 40  # Upper cutoff frequency

filtered_A = bandpass_filter(subset_A, lowcut, highcut, fs)
filtered_B = bandpass_filter(subset_B, lowcut, highcut, fs)
filtered_C = bandpass_filter(subset_C, lowcut, highcut, fs)
filtered_D = bandpass_filter(subset_D, lowcut, highcut, fs)
filtered_E = bandpass_filter(subset_E, lowcut, highcut, fs)


print(f"Filtered Subset A Shape: {filtered_A.shape}")

def plot_filtered_signals(subsets, sampling_rate=173.61):
    plt.figure(figsize=(12, 10))

    for i, subset in enumerate(subsets):
        # Select the first signal from each subset for plotting
        signal = subset[0]  # Use the first filtered signal in each subset
        time = np.arange(len(signal)) / sampling_rate

        # Create a subplot for each subset
        plt.subplot(len(subsets), 1, i + 1)
        plt.plot(time, signal, color='blue')
        plt.title(f'Filtered EEG Signal from Subset {chr(65 + i)}')  # 'A', 'B', etc.
        plt.xlabel("Time (seconds)")
        plt.ylabel("Amplitude")
        plt.grid(True)

    plt.tight_layout()  # Adjust layout to prevent overlap
    plt.show()

# Plot the filtered signals from each subset (A, B, C, D, E)
filtered_subsets = [filtered_A, filtered_B, filtered_C, filtered_D, filtered_E]
plot_filtered_signals(filtered_subsets)

"""# DATA PRE-PROCESSING (SEGMENTATION)"""

# Function to segment the EEG data into smaller time windows
def segment_eeg_data(data, window_size, fs):
    n_samples_per_window = 178
    segmented_data = []

    # Loop over each EEG signal
    for signal in data:
        # Split the signal into non-overlapping windows
        n_windows = len(signal) // n_samples_per_window
        for i in range(n_windows):
            start = i * n_samples_per_window
            end = start + n_samples_per_window
            segmented_data.append(signal[start:end])

    return np.array(segmented_data)

# Segment subset A into 1-second windows (173 samples per second)
window_size = 1  # seconds
segmented_A = segment_eeg_data(filtered_A, window_size, fs)
segmented_B = segment_eeg_data(filtered_B, window_size, fs)
segmented_C = segment_eeg_data(filtered_C, window_size, fs)
segmented_D = segment_eeg_data(filtered_D, window_size, fs)
segmented_E = segment_eeg_data(filtered_E, window_size, fs)


print(f"Segmented Subset A Shape: {segmented_A.shape}")  # Expected output: (n_segments, n_samples_per_window)

def plot_segmented_signals(segmented_subsets, sampling_rate=173.61, n_segments=3):
    plt.figure(figsize=(12, 10))

    for i, segmented_data in enumerate(segmented_subsets):
        # Plot the first few segments from each subset
        for j in range(n_segments):
            segment = segmented_data[j]  # Select the j-th segment
            time = np.arange(len(segment)) / sampling_rate  # Time axis for each segment

            # Create subplot for each segment
            plt.subplot(len(segmented_subsets), n_segments, i * n_segments + j + 1)
            plt.plot(time, segment, color='blue')
            plt.title(f'Subset {chr(65 + i)}, Segment {j + 1}')
            plt.xlabel("Time (seconds)")
            plt.ylabel("Amplitude")
            plt.grid(True)

    plt.tight_layout()  # Adjust layout for better visibility
    plt.show()

# List of segmented subsets to plot
segmented_subsets = [segmented_A, segmented_B, segmented_C, segmented_D, segmented_E]

# Plot segmented signals from each subset, showing 3 segments per subset
plot_segmented_signals(segmented_subsets, n_segments=1)

"""# Merging dataset"""

X = np.concatenate([segmented_A, segmented_B, segmented_C, segmented_D, segmented_E], axis=0)

# Step 2: Create labels for each subset
# Assuming 5 classes, one for each subset
y_A = np.zeros(len(segmented_A))  # Label 0 for subset A
y_B = np.zeros(len(segmented_B))   # Label 0 for subset B
y_C = np.zeros(len(segmented_C))  # Label 0 for subset C
y_D = np.zeros(len(segmented_D))  # Label 0 for subset D
y_E = np.ones(len(segmented_E))  # Label 1 for subset E

# Step 3: Concatenate all labels into a single array
y = np.concatenate([y_A, y_B, y_C, y_D, y_E], axis=0)

# Now, X is your feature dataset and y is your label dataset
print("X shape:", X.shape)
print("y shape:", y.shape)

y = y.reshape(-1, 1)
print("y shape after reshaping:", y.shape)  # Should print (11500, 1)

"""# Training neural network"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tensorflow.keras.initializers import RandomUniform
from sklearn.preprocessing import StandardScaler

# Assuming `X` has shape (11500, 178) and `y` is categorical with integer labels
# Convert y to one-hot encoding if it's a multi-class problem
num_classes = len(np.unique(y))
y = to_categorical(y, num_classes=num_classes)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

# Fit the scaler on the training data and transform both the training and test sets
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""**ANN MODEL**"""

# Define the ANN model
model = Sequential()
model.add(Dense(256, activation='relu', input_shape=(178,)))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='tanh'))
model.add(Dense(2, activation='sigmoid'))  # Use 'softmax' for multi-class

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=20, batch_size=100, validation_data=(X_test, y_test))

"""**Evaluate the model**"""

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_accuracy}")

# Optional: Predict and calculate accuracy for further evaluation
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)
accuracy = accuracy_score(y_true_classes, y_pred_classes)
print(f"Test Accuracy (calculated): {accuracy}")



from sklearn.metrics import confusion_matrix,classification_report

cm = confusion_matrix(y_true_classes, y_pred_classes)
print("Confusion Matrix:",cm)
print(classification_report(y_true_classes, y_pred_classes, target_names=['Normal', 'Epileptic']))

def plot_loss(history):
    plt.figure(figsize=(10, 6))
    plt.plot(history.history['loss'], label='Training Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.title("Loss vs. Epochs")
    plt.legend()
    plt.grid(True)
    plt.show()

plot_loss(history)

